<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Cron.Extensions.Expressions</PackageId>
    <Description>Fluent CRON expression builder for .NET</Description>
  </PropertyGroup>

  <PropertyGroup Label="AOT">
    <IsAotCompatible>true</IsAotCompatible>
    <PublishAot>false</PublishAot>
    <TrimMode>link</TrimMode>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Cron.Extensions.Expressions.Tests, PublicKey=$(CronExtensionsExpressionsPublicKey)" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>