name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    
    - name: Restore dependencies
      run: dotnet restore ./src
    
    - name: Build the project
      run: dotnet build ./src --no-restore --configuration Release

    - name: Run tests
      run: dotnet test ./src --no-build --verbosity normal --configuration Release
